"""Initial migration

Revision ID: b6c4dfce0b8f
Revises: e2caf354b234
Create Date: 2023-03-23 21:49:42.410026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c4dfce0b8f'
down_revision = 'e2caf354b234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
