version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    env_file:
      - ./config/.env.dev
    volumes:
      - postgres-db:/var/lib/postgresql/data
      
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'


volumes:
  postgres-db:
