version: '3.9'

services:
  api:
    image: api
    container_name: api
    build:
      context: ./api
      target: build
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    depends_on:
      - postgres
    environment:
      - APP_ENV=prod
    volumes:
      - ./config/.env.dev:/src/app/config/.env.dev
      - ./config/.env.prod:/src/app/config/.env.prod
      - ./api:/src/app

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    environment:
      - APP_ENV=prod
    volumes:
      - ./config/.env.dev:/src/app/config/.env.dev
      - ./config/.env.prod:/src/app/config/.env.prod
      - postgres-db:/var/lib/postgresql/data

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '3000:3000'
    volumes:
      - ./dashboard:/app/
  
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres-db:
