version: '3.9'

services:
  api:
    image: api
    container_name: api
    build:
      context: ./api
      target: build
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    # alembic upgrade head && 
    depends_on:
      - postgres
    volumes:
      - ./.env:/src/app/config/.env
      - ./api:/src/app

  # celery_worker:
  #   image: api
  #   container_name: celery_worker
  #   build:
  #     context: ./api
  #     target: build
  #   command: celery -A app.celery_task.celery:celery_app worker --loglevel=info
  #   depends_on:
  #     - api
  #     - redis
  #   volumes:
  #     - ./.env:/src/app/config/.env
  #     - ./api:/src/app
      
  # celery_beat:
  #   image: api
  #   container_name: celery_beat
  #   build:
  #     context: ./api
  #     target: build
  #   command: celery -A app.celery_task.celery:celery_app beat --loglevel=info --scheduler celery.beat.PersistentScheduler -s /celerybeat-schedule

  #   depends_on:
  #     - api
  #     - redis
  #   volumes:
  #     - ./.env:/src/app/config/.env
  #     - ./api:/src/app

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '3000:3000'
    volumes:
      - ./dashboard:/app/
  
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres-db: