version: '3.9'

services:
  api:
    image: api
    container_name: api
    build:
      context: ./api
      target: build
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    depends_on:
      - postgres
    volumes:
      - ./.env:/src/app/config/.env

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '3000:3000'
    volumes:
      - ./dashboard/dashboard:/app/
  
  # redis:
  #   image: redis
  #   container_name: redis

volumes:
  postgres-db: