"""Initial migration

Revision ID: 708f09c16884
Revises: ab0a07a2f8ba
Create Date: 2023-03-20 00:13:16.036430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '708f09c16884'
down_revision = 'ab0a07a2f8ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idpersona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OsId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_only', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_only', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rrhhid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='appointments_pkey')
    )
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###
